[package]
name = "rust-parallel-download"
version = "0.1.0"
authors = ["Joel Wright <joel.wright@gmail.com>"]

[dependencies]
docopt = ">0.6.79"
hyper = ">0.6.15"
chrono = ">0.2.20"
rustc-serialize = ">0.3.15"
url = ">0.2.20"

